apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-kubi-cloud
  namespace: front-public
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address use.d for ACME registration
    email: sanstrombraker@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-kubi-cloud
    # Enable the HTTP-01 challenge provide
    solvers:
    - http01:
        ingress:
          class: nginx

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-kubi-cloud
  namespace: back-private
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address use.d for ACME registration
    email: sanstrombraker@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-kubi-cloud
    # Enable the HTTP-01 challenge provide
    solvers:
    - http01:
        ingress:
          class: nginx