apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer-deployment
  namespace: back-private
  labels:
    app: indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexer
  template:
    metadata:
      labels:
        app: indexer
    spec:
      containers:
      - name: indexer
        image: {{ docker_image }}
        ports:
        - containerPort: 9090
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: indexer-service
  namespace: back-private
spec:
  type: LoadBalancer
  selector:
    app: indexer
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
