name: "Helm installation"
description: "Helm installation"
runs:
    using: composite
    steps:
      - name: Helm installation 🌎
        working-directory:  ${{ env.PROJECT_DIRECTORY }}
        shell: bash
        run: |-
            sudo curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
            sudo chmod 700 get_helm.sh
            sudo ./get_helm.sh