apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: back-app-pvc
  namespace: back-private
spec:
  storageClassName: standard-rwx
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: back-private
data:
  default.conf: |
    server {
        listen 80;
        index index.php index.html;
        error_log  /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;
        root /var/www/public;
        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
        location / {
            try_files $uri $uri/ /index.php?$query_string;
            gzip_static on;
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment-1
  namespace: back-private
  labels:
    app: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      restartPolicy: Always
      volumes:
      - name: back-app-volume
        persistentVolumeClaim:
          claimName: back-app-pvc
      - name: nginx-conf
        configMap:
          name: nginx-conf
      containers:
      - name: back
        image: {{ docker_image }}
        ports:
        - containerPort: 9000
        imagePullPolicy: Always
        volumeMounts:
        - name: back-app-volume
          mountPath: /var/www
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      - name: back-nginx
        image: nginx:1.17-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: back-app-volume
          mountPath: /var/www
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: back-service-1
  namespace: back-private
spec:
  type: LoadBalancer
  selector:
    app: back
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80