apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: front-public
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: {{ docker_image }}
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: front-public
spec:
  type: LoadBalancer
  selector:
    app: front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
