apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-deployment
  namespace: back-private
  labels:
    app: reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting
  template:
    metadata:
      labels:
        app: reporting
    spec:
      containers:
      - name: reporting
        image: {{ docker_image }}
        ports:
        - containerPort: 4000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: reporting-service
  namespace: back-private
spec:
  type: LoadBalancer
  selector:
    app: reporting
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
