apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-deployment
  namespace: back-private
  labels:
    app: reporting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reporting
  template:
    metadata:
      labels:
        app: reporting
    spec:
      containers:
      - name: reporting
        image: {{ docker_image }}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reporting-service
  namespace: back-private
spec:
  type: LoadBalancer
  selector:
    app: reporting
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
